version: '3.8'

services:
  dna-barcoding:
    build:
      context: .
      dockerfile: container/Dockerfile
    container_name: dna-barcoding
    image: dna-barcoding:latest
    volumes:
      # Mount the entire project directory
      - .:/workspace
      # Persist shell history
      - zsh-history:/root/.zsh_history
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
    command: zsh

volumes:
  zsh-history:
